apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.common.namespace }}
spec:
  replicas: {{ .Values.mysql.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  serviceName: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          env:
            {{- range $key, $_ := .Values.mysql.secrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Chart.Name }}-secrets
                  key: {{ $key }}
            {{- end }}
          ports:
            - name: mysql
              containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
              subPath: mysql
            - name: config-map
              mountPath: /docker-entrypoint-initdb.d
          resources:
            requests:
              cpu: {{ .Values.mysql.resources.requests.cpu }}
              memory: {{ .Values.mysql.resources.requests.memory }}
            limits:
              cpu: {{ .Values.mysql.resources.limits.cpu }}
              memory: {{ .Values.mysql.resources.limits.memory }}
          livenessProbe:
            exec:
              command: ['mysqladmin', 'ping']
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command: ['mysqladmin', 'ping']
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
      volumes:
        - name: config-map
          configMap:
            name: {{ .Chart.Name }}
      tolerations:
        {{- toYaml .Values.mysql.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.mysql.affinity | nindent 8 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.mysql.pvc.storage }}
